
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Dec 03 18:49:23 BRT 2025
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 10;
  public static final int PF = 8;
  public static final int POT = 6;
  public static final int MULT = 4;
  public static final int PA = 7;
  public static final int INTDIV = 9;
  public static final int EOF = 0;
  public static final int SUB = 3;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int SOMA = 2;
}

